### ISSUE TITLE
how to export assetbundle?

### ISSUE THREAD

**Issue by erikaemma** [enimaroah/SB3Utility#1]
couldn't find plugin for ExportAssetBundle()

**Comment by enimaroah** [comment]
You can neither export nor import an AssetBundle asset. Importing would break the file.

But you can "Dump AssetBundle" from the menu to see what is inside.

**Comment by erikaemma** [comment]
> You can neither export nor import an AssetBundle asset. Importing would break the file.
> 
> But you can "Dump AssetBundle" from the menu to see what is inside.

Thanks

**Comment by erikaemma** [comment]
> You can neither export nor import an AssetBundle asset. Importing would break the file.
> 
> But you can "Dump AssetBundle" from the menu to see what is inside.

Thanks
