### ISSUE TITLE
Please add support for KoikatsuSunshine .unity3d file

### ISSUE THREAD

**Issue by smartluo1833** [enimaroah/SB3Utility#6]
I'm trying to make KKS cloth mods, but I don't have SB3Utility version which can support KKS.
For example, drag in "co_shorts_00.unity3d" of  KoikatsuSunshine to SB3Utility, 
but the file is not loaded successfully.

**Comment by smartluo1833** [comment]
The problem was solved, I downloaded the old version.
SB3UtilityGUI version 21.2 can work.
Thanks!

**Comment by ShorneHua** [comment]
> The problem was solved, I downloaded the old version. SB3UtilityGUI version 21.2 can work. Thanks!

Hello, could you please provide the download website of version 21.2? It seems that the latest release on github is v21.0.3...
